=== disaster-robotics-proalertas/usv_sim_lsa/src/freefloating_gazebo_demo/scenes/UWSimScene.dtd
<!ELEMENT UWSimScene (oceanState?,simParams?,camera?,vehicle*,object*,rosInterfaces?)>

<!-- elementos oceanScene -->
<!ELEMENT oceanState (windx?,windy?,windSpeed?,depth?,reflectionDamping?,waveScale?,isNotChoppy?,choppyFactor?,crestFoamHeight?,oceanSurfaceHeight?,fog?,color?,attenuation?)>
<!ELEMENT simParams (disableShaders?,resw?,resh?,offsetp?,offsetr?,enablePhysics?,gravity?,physicsWater?)>
<!ELEMENT vehicle (name,file,jointValues?,position?,orientation?,virtualCamera*, rangeSensor*, objectPicker*, imu*, pressureSensor*, gpsSensor*, dvlSensor*, virtualRangeImage*,multibeamSensor*)>
<!ELEMENT virtualCamera (name,relativeTo,resw?,resh?,position?,orientation?,baseline?,frameId?, parameters?, showpath?)>
<!ELEMENT virtualRangeImage (name,relativeTo,resw?,resh?,position?,orientation?,parameters?)>
<!ELEMENT rangeSensor (name,relativeTo,range,visible?,position?,orientation?)>
<!ELEMENT objectPicker (name,relativeTo,range,position?,orientation?)>
<!ELEMENT imu (name,relativeTo,position?,orientation?, std?)>
<!ELEMENT pressureSensor (name,relativeTo,position?,orientation?, std?)>
<!ELEMENT gpsSensor (name,relativeTo,position?,orientation?, std?)>
<!ELEMENT dvlSensor (name,relativeTo,position?,orientation?, std?)>
<!ELEMENT multibeamSensor (name,relativeTo,position?,orientation?, initAngle,finalAngle, angleIncr,range)>
<!ELEMENT camera (freeMotion?,objectToTrack?,fov?,aspectRatio?,near?,far?,position?,lookAt?) >
<!ELEMENT object (name,file,position,orientation,offsetp?,offsetr?,physics?)>
<!ELEMENT rosInterfaces ((ROSOdomToPAT*)?, (PATToROSOdom*)?, (ArmToROSJointState*)?, (ROSJointStateToArm*)?, (VirtualCameraToROSImage*)?, (ROSImageToHUD*)?,(ROSTwistToPAT*)?, (RangeSensorToROSRange*)?, (ROSPoseToPAT*)?, (ImuToROSImu*)?, (PressureSensorToROS*)?, (GPSSensorToROS*)?, (DVLSensorToROS*)?, (RangeImageSensorToROSImage*)?,(multibeamSensorToLaserScan*)?)>

<!-- elementos comunes -->
<!ELEMENT position (x,y,z)>
<!ELEMENT orientation (r,p,y)>
<!ELEMENT offsetp (x,y,z)>
<!ELEMENT offsetr (x,y,z)>
<!ELEMENT lookAt (x,y,z)>
<!ELEMENT color (r,g,b)>

<!ELEMENT x (#PCDATA)>
<!ELEMENT y (#PCDATA)>
<!ELEMENT z (#PCDATA)>
<!ELEMENT r (#PCDATA)>
<!ELEMENT g (#PCDATA)>
<!ELEMENT b (#PCDATA)>
<!ELEMENT p (#PCDATA)>
<!ELEMENT std (#PCDATA)>


<!-- elementos oceanState -->
<!ELEMENT windx (#PCDATA)>
<!ELEMENT windy (#PCDATA)>
<!ELEMENT windSpeed (#PCDATA)>
<!ELEMENT depth (#PCDATA)>
<!ELEMENT reflectionDamping (#PCDATA)>
<!ELEMENT waveScale (#PCDATA)>
<!ELEMENT isNotChoppy (#PCDATA)>
<!ELEMENT choppyFactor (#PCDATA)>
<!ELEMENT crestFoamHeight (#PCDATA)>
<!ELEMENT oceanSurfaceHeight (#PCDATA)>
<!ELEMENT fog (density,color)>
<!ELEMENT attenuation (r,g,b)>

<!ELEMENT density (#PCDATA)>

<!-- elementos simParams -->
<!ELEMENT disableShaders (#PCDATA)>
<!ELEMENT eye_in_hand (#PCDATA)>
<!ELEMENT resw (#PCDATA)>
<!ELEMENT resh (#PCDATA)>
<!ELEMENT enablePhysics (#PCDATA)>
<!ELEMENT gravity (x,y,z)>
<!ELEMENT physicsWater (size,position,resolution)>
<!ELEMENT size (minX,maxX,minY,maxY,minZ,maxZ)>
<!ELEMENT resolution (#PCDATA)>
<!ELEMENT minX (#PCDATA)>
<!ELEMENT maxX (#PCDATA)>
<!ELEMENT minY (#PCDATA)>
<!ELEMENT maxY (#PCDATA)>
<!ELEMENT minZ (#PCDATA)>
<!ELEMENT maxZ (#PCDATA)>

<!--elementos camera -->
<!ELEMENT freeMotion (#PCDATA)>
<!ELEMENT fov (#PCDATA)>
<!ELEMENT aspectRatio (#PCDATA)>
<!ELEMENT near (#PCDATA)>
<!ELEMENT far (#PCDATA)>

<!ELEMENT objectToTrack (#PCDATA)>

<!-- elementos virtualCamera -->
<!ELEMENT relativeTo (#PCDATA)>
<!ELEMENT parameters (fx,fy,x0,y0,f,n,k)>

<!ELEMENT fx (#PCDATA)>
<!ELEMENT fy (#PCDATA)>
<!ELEMENT x0 (#PCDATA)>
<!ELEMENT y0 (#PCDATA)>
<!ELEMENT f (#PCDATA)>
<!ELEMENT n (#PCDATA)>
<!ELEMENT k (#PCDATA)>
<!ELEMENT baseline (#PCDATA)>
<!ELEMENT frameId (#PCDATA)>
<!ELEMENT showpath (#PCDATA)>

<!--elementos rangeSensor -->
<!ELEMENT range (#PCDATA)>
<!ELEMENT visible (#PCDATA)>

<!--elementos multibeamSensor -->
<!ELEMENT initAngle (#PCDATA)>
<!ELEMENT finalAngle (#PCDATA)>
<!ELEMENT angleIncr (#PCDATA)>

<!-- elementos vehicle -->
<!ELEMENT name (#PCDATA)>
<!ELEMENT file (#PCDATA)>
<!ELEMENT jointValues (joint+)>

<!ELEMENT joint (#PCDATA)>

<!-- elementos rosinterfaces -->
<!ELEMENT ROSOdomToPAT (topic,vehicleName, visualize?)>
<!ELEMENT PATToROSOdom  (topic, vehicleName, rate?)>
<!ELEMENT ArmToROSJointState  (topic, vehicleName, rate?)>
<!ELEMENT ROSJointStateToArm  (topic,vehicleName)>
<!ELEMENT VirtualCameraToROSImage (cameraName,imageTopic,infoTopic,rate?,depth?)>
<!ELEMENT RangeImageSensorToROSImage (cameraName,imageTopic,infoTopic,rate?)>
<!ELEMENT RangeSensorToROSRange (name,topic,rate?)>
<!ELEMENT ROSImageToHUD (width,height,posx?,posy?,scale?,blackWhite?,imageTopic,infoTopic?)>
<!ELEMENT ROSTwistToPAT (topic,vehicleName)>
<!ELEMENT ROSPoseToPAT (topic,vehicleName)>
<!ELEMENT ImuToROSImu (name, topic, rate?)>
<!ELEMENT PressureSensorToROS (name, topic, rate?)>
<!ELEMENT GPSSensorToROS (name, topic, rate?)>
<!ELEMENT DVLSensorToROS (name, topic, rate?)>
<!ELEMENT multibeamSensorToLaserScan (name, topic, rate?)>

<!ELEMENT width (#PCDATA)>
<!ELEMENT height (#PCDATA)>
<!ELEMENT posx (#PCDATA)>
<!ELEMENT posy (#PCDATA)>
<!ELEMENT blackWhite (#PCDATA)>
<!ELEMENT scale (#PCDATA)>
<!ELEMENT topic (#PCDATA)>
<!ELEMENT vehicleName (#PCDATA)>
<!ELEMENT rate (#PCDATA)>
<!ELEMENT cameraName (#PCDATA)>
<!ELEMENT imageTopic (#PCDATA)>
<!ELEMENT infoTopic (#PCDATA)>
<!ELEMENT visualize (#PCDATA)>

<!-- elementos vcamtoROSImage -->
<!ELEMENT cam (#PCDATA)>
<!ELEMENT info (#PCDATA)>

<!-- elementos physics -->
<!ELEMENT physics (mass?,inertia?,collisionShapeType?,linearDamping?,angularDamping?,linearFactor?,angularFactor?,isKinematic?)>
<!ELEMENT mass (#PCDATA)>
<!ELEMENT inertia (x,y,z)>
<!ELEMENT collisionShapeType (#PCDATA)>
<!ELEMENT linearDamping (#PCDATA)>
<!ELEMENT angularDamping (#PCDATA)>
<!ELEMENT linearFactor (x,y,z)>
<!ELEMENT angularFactor (x,y,z)>
<!ELEMENT isKinematic (#PCDATA)>

=== disaster-robotics-proalertas/usv_sim_lsa/src/underwater_simulation/uwsim/data/scenesAPAGAR/xacroExample.xml
<?xml version="1.0" ?>
<!-- =================================================================================== -->
<!-- |    This document was autogenerated by xacro from /home/lsa/ocean2/src/underwater_simulation/uwsim/data/scenes/xacroExample.xml.xacro | -->
<!-- |    EDITING THIS FILE BY HAND IS NOT RECOMMENDED                                 | -->
<!-- =================================================================================== -->
<!DOCTYPE UWSimScene
  SYSTEM 'UWSimScene.dtd'>
<UWSimScene xmlns:xacro="http://www.ros.org/wiki/xacro">
  <!-- oceanState macros -->
  <!-- simParameters macros -->
  <!-- camera macros -->
  <!-- vehicle macros -->
  <!-- AFAIK: There is no simple way to create a xacro macro for jointValues. -->
  <!-- <xacro:macro name="_joints">
<jointValues>
  <joint> 0 </joint>
  <joint> 0</joint>
  <joint> 2.2 </joint>
  <joint> 0 </joint>
  <joint>0.3 </joint>
</jointValues>
</xacro:macro> -->
  <!-- Virtual cameras macros -->
  <!-- Structured light projectors macros -->
  <!-- range sensor macros -->
  <!--Object picker macros -->
  <!-- imu macros -->
  <!--pressureSensor macros -->
  <!--gpsSensor macros -->
  <!--dvlSensor macros -->
  <!-- Virtual range image macros -->
  <!-- multibeam sensor macros -->
  <!-- Force sensor macros -->
  <!-- Dredge Tool macros -->
  <!-- Object macros -->
  <!-- Ros interfaces macros -->
  <!-- oceanState macros -->
  <!-- simParameters macros -->
  <!-- camera macros -->
  <!-- vehicle macros -->
  <!-- AFAIK: There is no simple way to create a xacro macro for jointValues. -->
  <!-- <xacro:macro name="_joints">
<jointValues>
  <joint> 0 </joint>
  <joint> 0</joint>
  <joint> 2.2 </joint>
  <joint> 0 </joint>
  <joint>0.3 </joint>
</jointValues>
</xacro:macro> -->
  <!-- Virtual cameras macros -->
  <!-- Structured light projectors macros -->
  <!-- range sensor macros -->
  <!--Object picker macros -->
  <!-- imu macros -->
  <!--pressureSensor macros -->
  <!--gpsSensor macros -->
  <!--dvlSensor macros -->
  <!-- Virtual range image macros -->
  <!-- multibeam sensor macros -->
  <!-- Force sensor macros -->
  <!-- Dredge Tool macros -->
  <!-- Object macros -->
  <!-- Ros interfaces macros -->
  <!-- oceanState macros -->
  <!-- simParameters macros -->
  <!-- camera macros -->
  <!-- vehicle macros -->
  <!-- AFAIK: There is no simple way to create a xacro macro for jointValues. -->
  <!-- <xacro:macro name="_joints">
<jointValues>
  <joint> 0 </joint>
  <joint> 0</joint>
  <joint> 2.2 </joint>
  <joint> 0 </joint>
  <joint>0.3 </joint>
</jointValues>
</xacro:macro> -->
  <!-- Virtual cameras macros -->
  <!-- Structured light projectors macros -->
  <!-- range sensor macros -->
  <!--Object picker macros -->
  <!-- imu macros -->
  <!--pressureSensor macros -->
  <!--gpsSensor macros -->
  <!--dvlSensor macros -->
  <!-- Virtual range image macros -->
  <!-- multibeam sensor macros -->
  <!-- Force sensor macros -->
  <!-- Dredge Tool macros -->
  <!-- Object macros -->
  <!-- Ros interfaces macros -->
  <!-- oceanState macros -->
  <!-- simParameters macros -->
  <!-- camera macros -->
  <!-- vehicle macros -->
  <!-- AFAIK: There is no simple way to create a xacro macro for jointValues. -->
  <!-- <xacro:macro name="_joints">
<jointValues>
  <joint> 0 </joint>
  <joint> 0</joint>
  <joint> 2.2 </joint>
  <joint> 0 </joint>
  <joint>0.3 </joint>
</jointValues>
</xacro:macro> -->
  <!-- Virtual cameras macros -->
  <!-- Structured light projectors macros -->
  <!-- range sensor macros -->
  <!--Object picker macros -->
  <!-- imu macros -->
  <!--pressureSensor macros -->
  <!--gpsSensor macros -->
  <!--dvlSensor macros -->
  <!-- Virtual range image macros -->
  <!-- multibeam sensor macros -->
  <!-- Force sensor macros -->
  <!-- Dredge Tool macros -->
  <!-- Object macros -->
  <!-- Ros interfaces macros -->
  <oceanState>
    <windx> 0.04 </windx>
    <windy> 0.04 </windy>
    <windSpeed> 12 </windSpeed>
    <depth> 1000 </depth>
    <reflectionDamping> 0.35 </reflectionDamping>
    <waveScale> 1e-07 </waveScale>
    <isNotChoppy> 0 </isNotChoppy>
    <choppyFactor> 2.5 </choppyFactor>
    <crestFoamHeight> 2.2 </crestFoamHeight>
    <oceanSurfaceHeight> 0 </oceanSurfaceHeight>
    <fog>
      <density> 0.1</density>
      <color>
        <r>0</r>
        <g>0.05</g>
        <b>0.3</b>
      </color>
    </fog>
    <color>
      <r>0.0</r>
      <g>0.05</g>
      <b>0.3</b>
    </color>
    <attenuation>
      <r>0.015</r>
      <g>0.0075</g>
      <b>0.005</b>
    </attenuation>
  </oceanState>
  <simParams>
    <disableShaders> 0 </disableShaders>
    <resw> 800 </resw>
    <resh> 600 </resh>
    <offsetp>
      <x>0</x>
      <y>0</y>
      <z>0</z>
    </offsetp>
    <offsetr>
      <x>3.141592654</x>
      <y>0</y>
      <z>-1.570796327</z>
    </offsetr>
    <enablePhysics> 0 </enablePhysics>
  </simParams>
  <camera>
    <freeMotion> 1 </freeMotion>
    <objectToTrack>girona500/base_link</objectToTrack>
    <fov> 60 </fov>
    <aspectRatio> 1.33 </aspectRatio>
    <near> 0.1 </near>
    <far> 10000 </far>
    <position>
      <x>-5</x>
      <y>-5</y>
      <z>8</z>
    </position>
    <lookAt>
      <x>0</x>
      <y>0</y>
      <z>0</z>
    </lookAt>
  </camera>
  <vehicle>
    <name>girona500</name>
    <file>data/scenes/g500ARM5.urdf</file>
    <jointValues>
      <joint> 0 </joint>
      <joint> 0</joint>
      <joint> 2.2 </joint>
      <joint> 0 </joint>
      <joint>0.3 </joint>
    </jointValues>
    <position>
      <x>0.2</x>
      <y>0</y>
      <z>2.0</z>
    </position>
    <orientation>
      <r>0</r>
      <p>0</p>
      <y>0</y>
    </orientation>
    <scaleFactor>
      <x>1</x>
      <y>1</y>
      <z>1</z>
    </scaleFactor>
    <virtualCamera>
      <name>bowtech1</name>
      <relativeTo>part0</relativeTo>
      <resw> 320</resw>
      <resh> 240</resh>
      <position>
        <x>-0.2</x>
        <y>-0.1</y>
        <z>0</z>
      </position>
      <orientation>
        <r>0</r>
        <p>3.141592654</p>
        <y>1.570796327</y>
      </orientation>
      <baseline>0</baseline>
      <frameId></frameId>
      <fovy>50</fovy>
      <showpath>0</showpath>
      <grayscale>0</grayscale>
      <std>0.005</std>
    </virtualCamera>
    <multibeamSensor>
      <name>multibeam</name>
      <relativeTo>part0</relativeTo>
      <visible>0</visible>
      <position>
        <x>-0.2</x>
        <y>0.1</y>
        <z>0</z>
      </position>
      <orientation>
        <r>3.141592654</r>
        <p>0</p>
        <y>3.141592654</y>
      </orientation>
      <initAngle>-60</initAngle>
      <finalAngle>60</finalAngle>
      <angleIncr>0.1</angleIncr>
      <range>10</range>
    </multibeamSensor>
  </vehicle>
  <object>
    <name>terrain</name>
    <file>terrain/CIRS/cirs_trident.osg</file>
    <position>
      <x>0</x>
      <y>0</y>
      <z>0</z>
    </position>
    <orientation>
      <r>0</r>
      <p>0</p>
      <y>0</y>
    </orientation>
    <scaleFactor>
      <x>1</x>
      <y>1</y>
      <z>1</z>
    </scaleFactor>
    <offsetp>
      <x>-1.5</x>
      <y>-3.0</y>
      <z>0</z>
    </offsetp>
    <offsetr>
      <x>3.141592654</x>
      <y>0</y>
      <z>-1.570796327</z>
    </offsetr>
    <physics>
      <mass> 0 </mass>
      <collisionShapeType>trimesh</collisionShapeType>
    </physics>
  </object>
  <object>
    <name>blackbox</name>
    <file>objects/blackbox_uib_trimesh.osg</file>
    <position>
      <x>0</x>
      <y>0</y>
      <z>4.7</z>
    </position>
    <orientation>
      <r>0</r>
      <p>3.141592654</p>
      <y>0</y>
    </orientation>
    <scaleFactor>
      <x>1</x>
      <y>1</y>
      <z>1</z>
    </scaleFactor>
    <offsetp>
      <x>0</x>
      <y>0</y>
      <z>0</z>
    </offsetp>
    <offsetr>
      <x>0</x>
      <y>0</y>
      <z>0</z>
    </offsetr>
    <physics>
      <mass> 15 </mass>
      <collisionShapeType>box</collisionShapeType>
    </physics>
  </object>
  <rosInterfaces>
    <ROSOdomToPAT>
      <topic> /dataNavigator </topic>
      <vehicleName> girona500 </vehicleName>
    </ROSOdomToPAT>
    <WorldToROSTF>
      <rootName> /world </rootName>
      <enableObjects> 1 </enableObjects>
    </WorldToROSTF>
    <ArmToROSJointState>
      <topic> /uwsim/joint_state </topic>
      <vehicleName> girona500 </vehicleName>
    </ArmToROSJointState>
    <ROSJointStateToArm>
      <topic> /uwsim/joint_state_command </topic>
      <vehicleName> girona500 </vehicleName>
    </ROSJointStateToArm>
    <VirtualCameraToROSImage>
      <cameraName> bowtech1 </cameraName>
      <imageTopic> /uwsim/camera1 </imageTopic>
      <infoTopic> /uwsim/camera1_info </infoTopic>
    </VirtualCameraToROSImage>
    <multibeamSensorToLaserScan>
      <name> multibeam </name>
      <topic> g500/multibeam </topic>
    </multibeamSensorToLaserScan>
  </rosInterfaces>
</UWSimScene>

=== disaster-robotics-proalertas/usv_sim_lsa/usv_sim/scenes/colregs/colregs_headon1.xml
<?xml version="1.0"?>

<!DOCTYPE UWSimScene SYSTEM "UWSimScene.dtd" >

<UWSimScene>
  <oceanState>
    <windx> 1.0 </windx>
    <windy> 1.0 </windy>
    <windSpeed> 0.0 </windSpeed>
    <depth> 100 </depth>
    <reflectionDamping> 0.35 </reflectionDamping>
    <waveScale> 5e-8 </waveScale>
    <isNotChoppy> 0 </isNotChoppy>
    <choppyFactor> -1.5 </choppyFactor>
    <crestFoamHeight> 1.2 </crestFoamHeight>
    <oceanSurfaceHeight> 0.75 </oceanSurfaceHeight>
    <fog>
      <density> 0.1 </density>
      <color>
        <r>0.017</r>
        <g>0.027</g>
        <b>0.079</b>
      </color>
    </fog>
    <color>
        <r>0.55</r>
        <g>0.45</g>
        <b>0.33</b>
    </color>
    <attenuation>
      <r>0.15</r>
      <g>0.15 </g>
      <b> 0.05 </b>
    </attenuation>
  </oceanState>
  
  <simParams>
    <disableShaders> 0 </disableShaders>
    <resw> 1152 </resw>
    <resh> 864 </resh>
  </simParams>

  <camera>
    <freeMotion> 1 </freeMotion>
    <objectToTrack>diffboat/base_link</objectToTrack>
    <fov> 60 </fov>
    <aspectRatio> 1.33 </aspectRatio>
    <near> 1 </near>
    <far> 10000 </far>
    <position>
      <x>340</x>
      <y>115 </y>
      <z>15 </z>
    </position> 
    <lookAt>
      <x>357</x>
      <y>115 </y>
      <z>5 </z>
    </lookAt>
  </camera>

  <vehicle>
    <name>diffboat1</name>
    <file>urdf/diffboat_uwsim.urdf</file>
    <jointValues>
      <joint> 0 </joint>
      <joint> 0 </joint>
    </jointValues>
     <position>
      <x> 430</x>
      <y> 115 </y>
      <z> 1 </z>
    </position>
    <orientation>
      <r>0 </r>
      <p>0 </p>
      <y>0 </y>
    </orientation>
  </vehicle>

  <vehicle>
    <name>diffboat2</name>
    <file>urdf/diffboat_uwsim.urdf</file>
    <jointValues>
      <joint> 0 </joint>
      <joint> 0 </joint>
    </jointValues>
     <position>
      <x> 480</x>
      <y> 115 </y>
      <z> 1 </z>
    </position>
    <orientation>
      <r>0 </r>
      <p>0 </p>
      <y>3.1415 </y>
    </orientation>
  </vehicle>

	<!-- <object>
    <name>terrain</name>
    <file>terrain/diluvio5/novo4.obj</file>
    <position>
      <x> 0</x>
      <y> 558 </y>
      <z> 0 </z>
    </position>
    <orientation>
      <r>0</r>
      <p>0 </p>
      <y>0 </y>
    </orientation>
  </object> -->

  	<object>
    <name>terrainA</name>
    <file>terrain/diluvio5/novo4a.obj</file>
    <position>
      <x> 0</x>
      <y> 558 </y>
      <z> 0 </z>
    </position>
    <orientation>
      <r>0</r>
      <p>0 </p>
      <y>0 </y>
    </orientation>
  </object>

	<object>
    <name>terrainB</name>
    <file>terrain/diluvio5/novo4b.obj</file>
    <position>
      <x> 0</x>
      <y> 558 </y>
      <z> 0 </z>
    </position>
    <orientation>
      <r>0</r>
      <p>0 </p>
      <y>0 </y>
    </orientation>
  </object>
  
  <object>
    <name>terrainP</name>
    <file>terrain/diluvio5/novo4p.obj</file>
    <position>
      <x> 0</x>
      <y> 558 </y>
      <z> 0 </z>
    </position>
    <orientation>
      <r>0</r>
      <p>0 </p>
      <y>0 </y>
    </orientation>
  </object>

  <rosInterfaces>   

    <ROSOdomToPAT>
      <topic> /diffboat1/state </topic>
      <vehicleName> diffboat1 </vehicleName>
    </ROSOdomToPAT>
    <ROSOdomToPAT>
      <topic> /diffboat2/state </topic>
      <vehicleName> diffboat2 </vehicleName>
    </ROSOdomToPAT>


<OceanSurfaceToROSOceanVehicle>
	<topic>/diffboat1/Surface/base_link</topic>
	<vehicleName>diffboat1</vehicleName>
	<linkName>base_link</linkName>
    </OceanSurfaceToROSOceanVehicle>  

	<OceanSurfaceToROSOceanVehicle>
	<topic>/diffboat1/Surface/center_r_link</topic>
	<vehicleName>diffboat1</vehicleName>
	<linkName>center_r_link</linkName>
    </OceanSurfaceToROSOceanVehicle>  

    <OceanSurfaceToROSOceanVehicle>
	<topic>/diffboat1/Surface/back_r_link</topic>
	<vehicleName>diffboat1</vehicleName>
	<linkName>back_r_link</linkName>
    </OceanSurfaceToROSOceanVehicle>  
    
    <OceanSurfaceToROSOceanVehicle>
	<topic>/diffboat1/Surface/back_l_link</topic>
	<vehicleName>diffboat1</vehicleName>
	<linkName>back_l_link</linkName>
    </OceanSurfaceToROSOceanVehicle>  

    <OceanSurfaceToROSOceanVehicle>
	<topic>/diffboat1/Surface/front_r_link</topic>
	<vehicleName>diffboat1</vehicleName>
	<linkName>front_r_link</linkName>
    </OceanSurfaceToROSOceanVehicle>  
    
    <OceanSurfaceToROSOceanVehicle>
	<topic>/diffboat1/Surface/front_l_link</topic>
	<vehicleName>diffboat1</vehicleName>
	<linkName>front_l_link</linkName>
    </OceanSurfaceToROSOceanVehicle> 

    <OceanSurfaceToROSOceanVehicle>
	<topic>/diffboat1/Surface/fwd_left</topic>
	<vehicleName>diffboat1</vehicleName>
	<linkName>fwd_left</linkName>
    </OceanSurfaceToROSOceanVehicle>   

    <OceanSurfaceToROSOceanVehicle>
	<topic>/diffboat1/Surface/fwd_right</topic>
	<vehicleName>diffboat1</vehicleName>
	<linkName>fwd_right</linkName>
    </OceanSurfaceToROSOceanVehicle> 

<OceanSurfaceToROSOceanVehicle>
	<topic>/diffboat2/Surface/base_link</topic>
	<vehicleName>diffboat2</vehicleName>
	<linkName>base_link</linkName>
    </OceanSurfaceToROSOceanVehicle>  

	<OceanSurfaceToROSOceanVehicle>
	<topic>/diffboat2/Surface/center_r_link</topic>
	<vehicleName>diffboat2</vehicleName>
	<linkName>center_r_link</linkName>
    </OceanSurfaceToROSOceanVehicle>  

    <OceanSurfaceToROSOceanVehicle>
	<topic>/diffboat2/Surface/back_r_link</topic>
	<vehicleName>diffboat2</vehicleName>
	<linkName>back_r_link</linkName>
    </OceanSurfaceToROSOceanVehicle>  
    
    <OceanSurfaceToROSOceanVehicle>
	<topic>/diffboat2/Surface/back_l_link</topic>
	<vehicleName>diffboat2</vehicleName>
	<linkName>back_l_link</linkName>
    </OceanSurfaceToROSOceanVehicle>  

    <OceanSurfaceToROSOceanVehicle>
	<topic>/diffboat2/Surface/front_r_link</topic>
	<vehicleName>diffboat2</vehicleName>
	<linkName>front_r_link</linkName>
    </OceanSurfaceToROSOceanVehicle>  
    
    <OceanSurfaceToROSOceanVehicle>
	<topic>/diffboat2/Surface/front_l_link</topic>
	<vehicleName>diffboat2</vehicleName>
	<linkName>front_l_link</linkName>
    </OceanSurfaceToROSOceanVehicle> 

    <OceanSurfaceToROSOceanVehicle>
	<topic>/diffboat2/Surface/fwd_left</topic>
	<vehicleName>diffboat2</vehicleName>
	<linkName>fwd_left</linkName>
    </OceanSurfaceToROSOceanVehicle>   

    <OceanSurfaceToROSOceanVehicle>
	<topic>/diffboat2/Surface/fwd_right</topic>
	<vehicleName>diffboat2</vehicleName>
	<linkName>fwd_right</linkName>
    </OceanSurfaceToROSOceanVehicle> 

	<ROSJointStateToArm> 
   		<topic>/diffboat1/joint_states</topic>
   		<vehicleName>diffboat1</vehicleName>
   	</ROSJointStateToArm>

     <ROSJointStateToArm> 
   		<topic>/diffboat2/joint_states</topic>
   		<vehicleName>diffboat2</vehicleName>
   	</ROSJointStateToArm>

  </rosInterfaces>
</UWSimScene>

=== disaster-robotics-proalertas/usv_sim_lsa/usv_sim/scenes/airboat_scenario3.xml
<?xml version="1.0"?>

<!DOCTYPE UWSimScene SYSTEM "UWSimScene.dtd" >

<UWSimScene>
  <oceanState>
    <windx> 1.0 </windx>
    <windy> 1.0 </windy>
    <windSpeed> 5.5 </windSpeed>
    <depth> 10000 </depth>
    <reflectionDamping> 0.35 </reflectionDamping>
    <waveScale> 5e-8 </waveScale>
    <isNotChoppy> 0 </isNotChoppy>
    <choppyFactor> -2.5 </choppyFactor>
    <crestFoamHeight> 2.2 </crestFoamHeight>
    <oceanSurfaceHeight> 1 </oceanSurfaceHeight>
    <fog>
      <density> 0.1 </density>
      <color>
        <r>0.017</r>
        <g>0.027</g>
        <b>0.079</b>
      </color>
    </fog>
    <color>
        <r>0.55</r>
        <g>0.45</g>
        <b>0.33</b>
    </color>
    <attenuation>
      <r>0.15</r>
      <g>0.15 </g>
      <b> 0.05 </b>
    </attenuation>
  </oceanState>
  
  <simParams>
    <disableShaders> 0 </disableShaders>
    <resw> 1152 </resw>
    <resh> 864 </resh>
  </simParams>

  <camera>
    <freeMotion> 1 </freeMotion>
    <objectToTrack>airboat/base_link</objectToTrack>
    <fov> 60 </fov>
    <aspectRatio> 1.33 </aspectRatio>
    <near> 1 </near>
    <far> 10000 </far>
    <position>
      <x>240</x>
      <y>82.5 </y>
      <z>25 </z>
    </position> 
    <lookAt>
      <x>260</x>
      <y>82.5 </y>
      <z>5 </z>
    </lookAt>
  </camera>

  <vehicle>
    <name>airboat</name>
    <file>urdf/airboat_uwsim.urdf</file>
    <jointValues>
      <joint> 0 </joint>
      <joint> 0 </joint>
    </jointValues>
     <position>
      <x> 250</x>
      <y> 95 </y>
      <z> 1 </z>
    </position>
    <orientation>
      <r>0 </r>
      <p>0 </p>
      <y>0 </y>
    </orientation>
  </vehicle>
  


   <vehicle>
    <name>buoy1</name>
    <file>urdf/buoy_uwsim.urdf</file>
    <position>
      <x> 250</x>
      <y> 100 </y>
      <z> 1 </z>
    </position>
    <orientation>
      <r>0</r>
      <p>0</p>
      <y>0</y>
    </orientation>
  </vehicle>
  
   <vehicle>
    <name>buoy2</name>
    <file>urdf/buoy_uwsim.urdf</file>
    <position>
      <x> 285</x>
      <y> 100 </y>
      <z> 1 </z>
    </position>
    <orientation>
      <r>0</r>
      <p>0</p>
      <y>0</y>
    </orientation>
  </vehicle>

   <vehicle>
    <name>buoy3</name>
    <file>urdf/buoy_uwsim.urdf</file>

    <position>
      <x> 250</x>
      <y> 65 </y>
      <z> 1 </z>
    </position>
    <orientation>
      <r>0</r>
      <p>0</p>
      <y>0</y>
    </orientation>
  </vehicle>

   <vehicle>
    <name>buoy4</name>
    <file>urdf/buoy_uwsim.urdf</file>

    <position>
      <x> 285</x>
      <y> 65 </y>
      <z> 1 </z>
    </position>
    <orientation>
      <r>0</r>
      <p>0</p>
      <y>0</y>
    </orientation>
  </vehicle>


	<object>
    <name>terrain</name>
    <file>terrain/diluvio5/novo4.obj</file>
    <position>
      <x> 0</x>
      <y> 558 </y>
      <z> 0 </z>
    </position>
    <orientation>
      <r>0</r>
      <p>0 </p>
      <y>0 </y>
    </orientation>
  </object>

  <rosInterfaces>   

    <ROSOdomToPAT>
      <topic> /airboat/state </topic>
      <vehicleName> airboat </vehicleName>
    </ROSOdomToPAT>

    <ROSOdomToPAT>
      <topic> /buoy1/state </topic>
      <vehicleName> buoy1 </vehicleName>
    </ROSOdomToPAT> 
    
    <ROSOdomToPAT>
      <topic> /buoy2/state </topic>
      <vehicleName> buoy2 </vehicleName>
    </ROSOdomToPAT> 
    
    <ROSOdomToPAT>
      <topic> /buoy3/state </topic>
      <vehicleName> buoy3 </vehicleName>
    </ROSOdomToPAT>    
    
    <ROSOdomToPAT>
      <topic> /buoy4/state </topic>
      <vehicleName> buoy4 </vehicleName>
    </ROSOdomToPAT> 

	<OceanSurfaceToROSOceanVehicle>
	<topic>/airboat/Surface/base_link</topic>
	<vehicleName>airboat</vehicleName>
	<linkName>base_link</linkName>
    </OceanSurfaceToROSOceanVehicle>  

	<OceanSurfaceToROSOceanVehicle>
	<topic>/airboat/Surface/center_r_link</topic>
	<vehicleName>airboat</vehicleName>
	<linkName>center_r_link</linkName>
    </OceanSurfaceToROSOceanVehicle>  

    <OceanSurfaceToROSOceanVehicle>
	<topic>/airboat/Surface/back_r_link</topic>
	<vehicleName>airboat</vehicleName>
	<linkName>back_r_link</linkName>
    </OceanSurfaceToROSOceanVehicle>  
    
    <OceanSurfaceToROSOceanVehicle>
	<topic>/airboat/Surface/back_l_link</topic>
	<vehicleName>airboat</vehicleName>
	<linkName>back_l_link</linkName>
    </OceanSurfaceToROSOceanVehicle>  

    <OceanSurfaceToROSOceanVehicle>
	<topic>/airboat/Surface/front_r_link</topic>
	<vehicleName>airboat</vehicleName>
	<linkName>front_r_link</linkName>
    </OceanSurfaceToROSOceanVehicle>  
    
    <OceanSurfaceToROSOceanVehicle>
	<topic>/airboat/Surface/front_l_link</topic>
	<vehicleName>airboat</vehicleName>
	<linkName>front_l_link</linkName>
    </OceanSurfaceToROSOceanVehicle> 
   
     <OceanSurfaceToROSOceanVehicle>
	<topic>/airboat/Surface/fwd</topic>
	<vehicleName>airboat</vehicleName>
	<linkName>fwd</linkName>
    </OceanSurfaceToROSOceanVehicle>  
     
    <OceanSurfaceToROSOceanVehicle>
	<topic>/buoy1/Surface/link</topic>
	<vehicleName>buoy1</vehicleName>
	<linkName>link</linkName>
    </OceanSurfaceToROSOceanVehicle>
    
    <OceanSurfaceToROSOceanVehicle>
	<topic>/buoy2/Surface/link</topic>
	<vehicleName>buoy2</vehicleName>
	<linkName>link</linkName>
    </OceanSurfaceToROSOceanVehicle> 
    
    <OceanSurfaceToROSOceanVehicle>
	<topic>/buoy3/Surface/link</topic>
	<vehicleName>buoy3</vehicleName>
	<linkName>link</linkName>
    </OceanSurfaceToROSOceanVehicle>  


    <OceanSurfaceToROSOceanVehicle>
	<topic>/buoy4/Surface/link</topic>
	<vehicleName>buoy4</vehicleName>
	<linkName>link</linkName>
    </OceanSurfaceToROSOceanVehicle>
        
	<ROSJointStateToArm> 
   		<topic>/airboat/joint_states</topic>
   		<vehicleName>airboat</vehicleName>
   	</ROSJointStateToArm>

  </rosInterfaces>
</UWSimScene>
