=== disaster-robotics-proalertas/usv_sim_lsa/src/freefloating_gazebo_demo/scenes/UWSimScene.dtd
<!ELEMENT UWSimScene (oceanState?,simParams?,camera?,vehicle*,object*,rosInterfaces?)>

<!-- elementos oceanScene -->
<!ELEMENT oceanState (windx?,windy?,windSpeed?,depth?,reflectionDamping?,waveScale?,isNotChoppy?,choppyFactor?,crestFoamHeight?,oceanSurfaceHeight?,fog?,color?,attenuation?)>
<!ELEMENT simParams (disableShaders?,resw?,resh?,offsetp?,offsetr?,enablePhysics?,gravity?,physicsWater?)>
<!ELEMENT vehicle (name,file,jointValues?,position?,orientation?,virtualCamera*, rangeSensor*, objectPicker*, imu*, pressureSensor*, gpsSensor*, dvlSensor*, virtualRangeImage*,multibeamSensor*)>
<!ELEMENT virtualCamera (name,relativeTo,resw?,resh?,position?,orientation?,baseline?,frameId?, parameters?, showpath?)>
<!ELEMENT virtualRangeImage (name,relativeTo,resw?,resh?,position?,orientation?,parameters?)>
<!ELEMENT rangeSensor (name,relativeTo,range,visible?,position?,orientation?)>
<!ELEMENT objectPicker (name,relativeTo,range,position?,orientation?)>
<!ELEMENT imu (name,relativeTo,position?,orientation?, std?)>
<!ELEMENT pressureSensor (name,relativeTo,position?,orientation?, std?)>
<!ELEMENT gpsSensor (name,relativeTo,position?,orientation?, std?)>
<!ELEMENT dvlSensor (name,relativeTo,position?,orientation?, std?)>
<!ELEMENT multibeamSensor (name,relativeTo,position?,orientation?, initAngle,finalAngle, angleIncr,range)>
<!ELEMENT camera (freeMotion?,objectToTrack?,fov?,aspectRatio?,near?,far?,position?,lookAt?) >
<!ELEMENT object (name,file,position,orientation,offsetp?,offsetr?,physics?)>
<!ELEMENT rosInterfaces ((ROSOdomToPAT*)?, (PATToROSOdom*)?, (ArmToROSJointState*)?, (ROSJointStateToArm*)?, (VirtualCameraToROSImage*)?, (ROSImageToHUD*)?,(ROSTwistToPAT*)?, (RangeSensorToROSRange*)?, (ROSPoseToPAT*)?, (ImuToROSImu*)?, (PressureSensorToROS*)?, (GPSSensorToROS*)?, (DVLSensorToROS*)?, (RangeImageSensorToROSImage*)?,(multibeamSensorToLaserScan*)?)>

<!-- elementos comunes -->
<!ELEMENT position (x,y,z)>
<!ELEMENT orientation (r,p,y)>
<!ELEMENT offsetp (x,y,z)>
<!ELEMENT offsetr (x,y,z)>
<!ELEMENT lookAt (x,y,z)>
<!ELEMENT color (r,g,b)>

<!ELEMENT x (#PCDATA)>
<!ELEMENT y (#PCDATA)>
<!ELEMENT z (#PCDATA)>
<!ELEMENT r (#PCDATA)>
<!ELEMENT g (#PCDATA)>
<!ELEMENT b (#PCDATA)>
<!ELEMENT p (#PCDATA)>
<!ELEMENT std (#PCDATA)>


<!-- elementos oceanState -->
<!ELEMENT windx (#PCDATA)>
<!ELEMENT windy (#PCDATA)>
<!ELEMENT windSpeed (#PCDATA)>
<!ELEMENT depth (#PCDATA)>
<!ELEMENT reflectionDamping (#PCDATA)>
<!ELEMENT waveScale (#PCDATA)>
<!ELEMENT isNotChoppy (#PCDATA)>
<!ELEMENT choppyFactor (#PCDATA)>
<!ELEMENT crestFoamHeight (#PCDATA)>
<!ELEMENT oceanSurfaceHeight (#PCDATA)>
<!ELEMENT fog (density,color)>
<!ELEMENT attenuation (r,g,b)>

<!ELEMENT density (#PCDATA)>

<!-- elementos simParams -->
<!ELEMENT disableShaders (#PCDATA)>
<!ELEMENT eye_in_hand (#PCDATA)>
<!ELEMENT resw (#PCDATA)>
<!ELEMENT resh (#PCDATA)>
<!ELEMENT enablePhysics (#PCDATA)>
<!ELEMENT gravity (x,y,z)>
<!ELEMENT physicsWater (size,position,resolution)>
<!ELEMENT size (minX,maxX,minY,maxY,minZ,maxZ)>
<!ELEMENT resolution (#PCDATA)>
<!ELEMENT minX (#PCDATA)>
<!ELEMENT maxX (#PCDATA)>
<!ELEMENT minY (#PCDATA)>
<!ELEMENT maxY (#PCDATA)>
<!ELEMENT minZ (#PCDATA)>
<!ELEMENT maxZ (#PCDATA)>

<!--elementos camera -->
<!ELEMENT freeMotion (#PCDATA)>
<!ELEMENT fov (#PCDATA)>
<!ELEMENT aspectRatio (#PCDATA)>
<!ELEMENT near (#PCDATA)>
<!ELEMENT far (#PCDATA)>

<!ELEMENT objectToTrack (#PCDATA)>

<!-- elementos virtualCamera -->
<!ELEMENT relativeTo (#PCDATA)>
<!ELEMENT parameters (fx,fy,x0,y0,f,n,k)>

<!ELEMENT fx (#PCDATA)>
<!ELEMENT fy (#PCDATA)>
<!ELEMENT x0 (#PCDATA)>
<!ELEMENT y0 (#PCDATA)>
<!ELEMENT f (#PCDATA)>
<!ELEMENT n (#PCDATA)>
<!ELEMENT k (#PCDATA)>
<!ELEMENT baseline (#PCDATA)>
<!ELEMENT frameId (#PCDATA)>
<!ELEMENT showpath (#PCDATA)>

<!--elementos rangeSensor -->
<!ELEMENT range (#PCDATA)>
<!ELEMENT visible (#PCDATA)>

<!--elementos multibeamSensor -->
<!ELEMENT initAngle (#PCDATA)>
<!ELEMENT finalAngle (#PCDATA)>
<!ELEMENT angleIncr (#PCDATA)>

<!-- elementos vehicle -->
<!ELEMENT name (#PCDATA)>
<!ELEMENT file (#PCDATA)>
<!ELEMENT jointValues (joint+)>

<!ELEMENT joint (#PCDATA)>

<!-- elementos rosinterfaces -->
<!ELEMENT ROSOdomToPAT (topic,vehicleName, visualize?)>
<!ELEMENT PATToROSOdom  (topic, vehicleName, rate?)>
<!ELEMENT ArmToROSJointState  (topic, vehicleName, rate?)>
<!ELEMENT ROSJointStateToArm  (topic,vehicleName)>
<!ELEMENT VirtualCameraToROSImage (cameraName,imageTopic,infoTopic,rate?,depth?)>
<!ELEMENT RangeImageSensorToROSImage (cameraName,imageTopic,infoTopic,rate?)>
<!ELEMENT RangeSensorToROSRange (name,topic,rate?)>
<!ELEMENT ROSImageToHUD (width,height,posx?,posy?,scale?,blackWhite?,imageTopic,infoTopic?)>
<!ELEMENT ROSTwistToPAT (topic,vehicleName)>
<!ELEMENT ROSPoseToPAT (topic,vehicleName)>
<!ELEMENT ImuToROSImu (name, topic, rate?)>
<!ELEMENT PressureSensorToROS (name, topic, rate?)>
<!ELEMENT GPSSensorToROS (name, topic, rate?)>
<!ELEMENT DVLSensorToROS (name, topic, rate?)>
<!ELEMENT multibeamSensorToLaserScan (name, topic, rate?)>

<!ELEMENT width (#PCDATA)>
<!ELEMENT height (#PCDATA)>
<!ELEMENT posx (#PCDATA)>
<!ELEMENT posy (#PCDATA)>
<!ELEMENT blackWhite (#PCDATA)>
<!ELEMENT scale (#PCDATA)>
<!ELEMENT topic (#PCDATA)>
<!ELEMENT vehicleName (#PCDATA)>
<!ELEMENT rate (#PCDATA)>
<!ELEMENT cameraName (#PCDATA)>
<!ELEMENT imageTopic (#PCDATA)>
<!ELEMENT infoTopic (#PCDATA)>
<!ELEMENT visualize (#PCDATA)>

<!-- elementos vcamtoROSImage -->
<!ELEMENT cam (#PCDATA)>
<!ELEMENT info (#PCDATA)>

<!-- elementos physics -->
<!ELEMENT physics (mass?,inertia?,collisionShapeType?,linearDamping?,angularDamping?,linearFactor?,angularFactor?,isKinematic?)>
<!ELEMENT mass (#PCDATA)>
<!ELEMENT inertia (x,y,z)>
<!ELEMENT collisionShapeType (#PCDATA)>
<!ELEMENT linearDamping (#PCDATA)>
<!ELEMENT angularDamping (#PCDATA)>
<!ELEMENT linearFactor (x,y,z)>
<!ELEMENT angularFactor (x,y,z)>
<!ELEMENT isKinematic (#PCDATA)>

=== disaster-robotics-proalertas/usv_sim_lsa/install_isolated/share/uwsim/data/scenes/shipwreck.xml
<?xml version="1.0"?>

<!DOCTYPE UWSimScene SYSTEM "UWSimScene.dtd" >

<UWSimScene>
  <oceanState>
    <windx> 1.0 </windx>
    <windy> 1.0 </windy>
    <windSpeed> 12 </windSpeed>
    <depth> 10000 </depth>
    <reflectionDamping> 0.35 </reflectionDamping>
    <waveScale> 1e-8 </waveScale>
    <isNotChoppy> 0 </isNotChoppy>
    <choppyFactor> -2.5 </choppyFactor>
    <crestFoamHeight> 2.2 </crestFoamHeight>
    <oceanSurfaceHeight> 0 </oceanSurfaceHeight>
    <fog>
      <density> 0.1 </density>
      <color>
	<r>0.017</r>
	<g>0.027</g>
	<b>0.079</b>
      </color>
    </fog>
    <color>
	<r>0.017</r>
	<g>0.027</g>
	<b>0.079</b>
    </color>
    <attenuation>
      <r>0.015</r>
      <g>0.0075 </g>
      <b> 0.005 </b>
    </attenuation>
  </oceanState>

  <simParams>
    <disableShaders> 0 </disableShaders>
    <resw> 800 </resw>
    <resh> 600 </resh>
  </simParams>

  <camera>
    <freeMotion> 1 </freeMotion>
    <objectToTrack>girona500_RAUVI/base_link</objectToTrack>
    <fov> 60 </fov>
    <aspectRatio> 1.33 </aspectRatio>
    <near> 1 </near>
    <far> 10000 </far>
    <position>
      <x>16</x>
      <y>9 </y>
      <z>-7 </z>
    </position> 
    <lookAt>
      <x>5</x>
      <y>7 </y>
      <z>-10 </z>
    </lookAt>
  </camera>

 <vehicle>
    <name>girona500_RAUVI</name>
    <file>data/scenes/g500ARM5.urdf</file>
    <jointValues>
      <joint> 0 </joint>
      <joint> M_PI_4</joint>
      <joint> M_PI_4 </joint>
      <joint> 0 </joint>
      <joint>-0.3 </joint>
    </jointValues>
    <position>
      <x> 5</x>
      <y> 7 </y>
      <z> -10 </z>
    </position>
    <orientation>
      <r>3.1415</r>
      <p>0 </p>
      <y>0 </y>
    </orientation>
  </vehicle>

  <vehicle>
    <name>girona500_TRIDENT</name>
    <file>data/scenes/g500ARM5.urdf</file>
    <jointValues>
      <joint> 0 </joint>
      <joint> M_PI_4</joint>
      <joint> M_PI_4 </joint>
      <joint> 0 </joint>
      <joint>-0.3 </joint>
    </jointValues>
    <position>
      <x> 7</x>
      <y> 5 </y>
      <z> -11 </z>
    </position>
    <orientation>
      <r>3.1415</r>
      <p>0 </p>
      <y>1.57 </y>
    </orientation>
  </vehicle>

  <object>
    <name>terrain</name>
    <file>terrain/shipwreck/terrain.ive</file>
    <position>
      <x> 0</x>
      <y> 0 </y>
      <z> 0 </z>
    </position>
    <orientation>
      <r>0</r>
      <p>0 </p>
      <y>0 </y>
    </orientation>
    <physics>
      <mass> 0 </mass>
      <collisionShapeType> trimesh </collisionShapeType>
    </physics>
  </object>

  <rosInterfaces>
    <ROSOdomToPAT>
      <topic> /dataNavigator_G500RAUVI </topic>
      <vehicleName> girona500_RAUVI </vehicleName>
    </ROSOdomToPAT>
    <ROSOdomToPAT>
      <topic> /dataNavigator_G500TRIDENT </topic>
      <vehicleName> girona500_TRIDENT </vehicleName>
    </ROSOdomToPAT>
    <PATToROSOdom>
      <topic> /uwsim/girona500_odom_RAUVI </topic>
      <vehicleName> girona500_RAUVI </vehicleName>
    </PATToROSOdom>
    <PATToROSOdom>
      <topic> /uwsim/girona500_odom_TRIDENT </topic>
      <vehicleName> girona500_TRIDENT </vehicleName>
    </PATToROSOdom>
    <WorldToROSTF>
      <rootName> world </rootName>
      <enableObjects> 0 </enableObjects>
      <rate>10</rate>
    </WorldToROSTF>
  </rosInterfaces>

</UWSimScene>

=== disaster-robotics-proalertas/usv_sim_lsa/src/usv_sim/scenes/sailboat.xml
<?xml version="1.0"?>

<!DOCTYPE UWSimScene SYSTEM "UWSimScene.dtd" >

<UWSimScene>
  <oceanState>
    <windx> 1.0 </windx>
    <windy> 1.0 </windy>
    <windSpeed> 6 </windSpeed>
    <depth> 10000 </depth>
    <reflectionDamping> 0.35 </reflectionDamping>
    <waveScale> 1e-8 </waveScale>
    <isNotChoppy> 0 </isNotChoppy>
    <choppyFactor> -2.5 </choppyFactor>
    <crestFoamHeight> 2.2 </crestFoamHeight>
    <oceanSurfaceHeight> 0 </oceanSurfaceHeight>
    <fog>
      <density> 0.1 </density>
      <color>
        <r>0.017</r>
        <g>0.027</g>
        <b>0.079</b>
      </color>
    </fog>
    <color>
        <r>0.017</r>
        <g>0.027</g>
        <b>0.079</b>
    </color>
    <attenuation>
      <r>0.015</r>
      <g>0.0075 </g>
      <b> 0.005 </b>
    </attenuation>
  </oceanState>
  
  <simParams>
    <disableShaders> 0 </disableShaders>
    <resw> 800 </resw>
    <resh> 600 </resh>
  </simParams>

  <camera>
    <freeMotion> 1 </freeMotion>
    <objectToTrack>g500/base_link</objectToTrack>
    <fov> 60 </fov>
    <aspectRatio> 1.33 </aspectRatio>
    <near> 1 </near>
    <far> 10000 </far>
    <position>
      <x>-5</x>
      <y>4 </y>
      <z>-7 </z>
    </position> 
    <lookAt>
      <x>5</x>
      <y>7 </y>
      <z>-10 </z>
    </lookAt>
  </camera>

  <vehicle>
    <name>sailboat</name>
    <file>urdf/sailboat_uwsim.urdf</file>
    <jointValues>
      <joint> 0 </joint>
      <joint> 0 </joint>
    </jointValues>
     <position>
      <x> 0</x>
      <y> 0 </y>
      <z> -1 </z>
    </position>
    <orientation>
      <r>0</r>
      <p>0 </p>
      <y>0 </y>
    </orientation>
  </vehicle>
  
   <object>
    <name>terrain</name>
    <file>terrain/shipwreck/terrain.ive</file>
    <position>
      <x> 0</x>
      <y> 0 </y>
      <z> 0 </z>
    </position>
    <orientation>
      <r>0</r>
      <p>0 </p>
      <y>0 </y>
    </orientation>
  </object>

  <rosInterfaces>      

    <ROSOdomToPAT>
      <topic> /sailboat/state </topic>
      <vehicleName> sailboat </vehicleName>
    </ROSOdomToPAT>

    <OceanSurfaceToROSOceanVehicle>
	<topic>/sailboat/Surface</topic>
	<vehicleName>sailboat</vehicleName>
    </OceanSurfaceToROSOceanVehicle>  
   
  </rosInterfaces>
</UWSimScene>

=== disaster-robotics-proalertas/usv_sim_lsa/usv_sim/scenes/sailboat_scenario0.xml
<?xml version="1.0"?>

<!DOCTYPE UWSimScene SYSTEM "UWSimScene.dtd" >

<UWSimScene>
  <oceanState>
    <windx> 1 </windx>
    <windy> 1 </windy>
    <windSpeed> 2.2 </windSpeed>
    <depth> 10000 </depth>
    <reflectionDamping> 0.35 </reflectionDamping>
    <waveScale> 1e-7 </waveScale>
    <isNotChoppy> 0 </isNotChoppy>
    <choppyFactor> -2.5 </choppyFactor>
    <crestFoamHeight> 2.2 </crestFoamHeight>
    <oceanSurfaceHeight> 1 </oceanSurfaceHeight>
    <fog>
      <density> 0.1 </density>
      <color>
        <r>0.017</r>
        <g>0.027</g>
        <b>0.079</b>
      </color>
    </fog>
    <color>
        <r>0.55</r>
        <g>0.45</g>
        <b>0.33</b>
    </color>
    <attenuation>
      <r>0.15</r>
      <g>0.15 </g>
      <b> 0.05 </b>
    </attenuation>
  </oceanState>
  
  <simParams>
    <disableShaders> 0 </disableShaders>
    <resw> 1152 </resw>
    <resh> 864 </resh>
  </simParams>

  <camera>
    <freeMotion> 1 </freeMotion>
    <objectToTrack>sailboat/base_link</objectToTrack>
    <fov> 60 </fov>
    <aspectRatio> 1.33 </aspectRatio>
    <near> 1 </near>
    <far> 10000 </far>
    <position>
      <x>135</x>
      <y>150 </y>
      <z>15 </z>
    </position> 
    <lookAt>
      <x>145</x>
      <y>150 </y>
      <z>5 </z>
    </lookAt>
  </camera>

  <vehicle>
    <name>sailboat</name>
    <file>urdf/sailboat_uwsim.urdf</file>
    <jointValues>
      <joint> 0 </joint>
      <joint> 0 </joint>
    </jointValues>
     <position>
      <x> 145 </x>
      <y> 150 </y>
      <z> 1.13 </z>
    </position>
    <orientation>
      <r>0 </r>
      <p>0 </p>
      <y>0 </y>
    </orientation>
  </vehicle>

  <rosInterfaces>   

    <ROSOdomToPAT>
      <topic> /sailboat/state </topic>
      <vehicleName> sailboat </vehicleName>
    </ROSOdomToPAT>

	<OceanSurfaceToROSOceanVehicle>
	<topic>/sailboat/Surface/base_link</topic>
	<vehicleName>sailboat</vehicleName>
	<linkName>base_link</linkName>
    </OceanSurfaceToROSOceanVehicle>  

	<OceanSurfaceToROSOceanVehicle>
	<topic>/sailboat/Surface/center_r_link</topic>
	<vehicleName>sailboat</vehicleName>
	<linkName>center_r_link</linkName>
    </OceanSurfaceToROSOceanVehicle>  

    <OceanSurfaceToROSOceanVehicle>
	<topic>/sailboat/Surface/back_r_link</topic>
	<vehicleName>sailboat</vehicleName>
	<linkName>back_r_link</linkName>
    </OceanSurfaceToROSOceanVehicle>  
    
    <OceanSurfaceToROSOceanVehicle>
	<topic>/sailboat/Surface/back_l_link</topic>
	<vehicleName>sailboat</vehicleName>
	<linkName>back_l_link</linkName>
    </OceanSurfaceToROSOceanVehicle>  

    <OceanSurfaceToROSOceanVehicle>
	<topic>/sailboat/Surface/front_r_link</topic>
	<vehicleName>sailboat</vehicleName>
	<linkName>front_r_link</linkName>
    </OceanSurfaceToROSOceanVehicle>  
    
    <OceanSurfaceToROSOceanVehicle>
	<topic>/sailboat/Surface/front_l_link</topic>
	<vehicleName>sailboat</vehicleName>
	<linkName>front_l_link</linkName>
    </OceanSurfaceToROSOceanVehicle>  
        
	<ROSJointStateToArm> 
   		<topic>/sailboat/joint_states</topic>
   		<vehicleName>sailboat</vehicleName>
   	</ROSJointStateToArm>

  </rosInterfaces>
</UWSimScene>
